### ISSUE TITLE
Add missing files

### ISSUE THREAD

**Issue by PVince81** [owncloud/user_external#3]
## Initial files

- [x] Docs
    - [x] README.md (typos fixed in #18 )
    - [x] .github folder (issue template, PR template) #18
- [x] Scripts
    - [x] Makefile
- [ ] Dependency
    - [x] composer.json
    - [ ] package.json (if JS code intended)

## Translations

TODO: how to setup transifex

## Code validation

- [x] Setup php-cs-fixer for code style enforcement #10 
- [x] Setup phan static code analysis #15 
- [x] Setup phpstan static code analysis #16 

## Unit tests

- [x] Setup phpunit for PHP tests #14 
- [ ] Run phpunit in drone

**Comment by mmattel** [comment]
In case there is a documentation change necessary: https://github.com/owncloud/docs/blob/395ab53466f45000ed2f6568f5f484e90aa37b16/modules/administration_manual/pages/configuration/user/user_auth_ftp_smb_imap.adoc

**Comment by phil-davis** [comment]
I added the `QA-team` label so that we notice this some time, and can set up drone CI, Makefile etc.

**Comment by phil-davis** [comment]
@PVince81 the outstanding items are:
- [ ] review `README.md` to see if what it says is true (someone who actually knows needs to do that)
- [ ] make the unit tests actually run and pass (locally and in drone). It looks like they need various `ftp`, `imap` and/or `smb` servers running and the tests check connecting (they are "integration" or "acceptance" tests rather than true "unit" tests.

Do I spend time working out what "magic environment" is needed for each of `ftpTest` `imapTest` and `smbTest` - or if someone knows then they could describe what environment is expected for each test and then I can easily make that happen in drone.

**Comment by phil-davis** [comment]
@micbar what is the priority here?
Someone in QA (me?) could spend time trying to get the "unit" tests running in drone/
Someone else needs to review `README.md`

**Comment by phil-davis** [comment]
@micbar or @PVince81 ping.
Please read above posts and let me know what effort and who should move this forward.

**Comment by DeepDiver1975** [comment]
No prio on tests from my personal POV. We deliver the code as is.

readme looks good as well

case closed from my pov
