### ISSUE TITLE
[decouple] External User Support 0.5.0

### ISSUE THREAD

**Issue by PVince81** [owncloud/user_external#5]
### Reason

- Decoupling release cycle from core so we can tag the app independently

### Tasks

- [x] add changelog
- [x] add Makefile

### QA

- [x] Create **QA Milestone**
- [x] Move items from `development` to `qa`
- [x] Create release branch with the format "release-$version"
- [x] Create "$version Testplan" #6

### Documentation

- [ ] Changes in the docs needed?

### Marketing

- [ ] Ping RocketChat channel #marketing
- [ ] Check/adapt info.xml stuff
- [ ] Check/adapt screenshot
- [ ] Blog post or other communication if applicable

### Build

All actions to be done on the release branch from here:
- [x] Bump version in info.xml (no version suffix)
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version' (final release date unknown)

#### Beta/RC

- [x] Create github tag for 'v${version}RC1' on release branch
- [x] Build and sign RC tarball from github tag 'v${version}RC1' (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries => https://github.com/owncloud/user_external/releases
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch

#### Final

- [x] Create github tag for final 'v${version}' on release branch
- [x] Build and sign final tarball from github tag 'v${version}' (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Smoke test tarball (at least install + enable)

### Publishing

- [x] Send mail to release-coordination with link to this ticket and to the changelog

### Post-release

- [x] Rename QA milestone to '$version'
- [x] Add a new 'Unreleased' section in CHANGELOG.md and add release date '$version - $currentDate' (ex: 3.1.5 - 2018-08-01)
- [x] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number: https://github.com/owncloud/user_external/pull/8

**Comment by PVince81** [comment]
RC1 needs smoke testing: https://github.com/owncloud/user_external/releases

**Comment by PVince81** [comment]
note: diff between stable10 and master is empty

**Comment by PVince81** [comment]
diff between 10.1.1 shipped version and the above tarball is minimal, no code changes

**Comment by individual-it** [comment]
@PVince81 fixed the link of RC1 as it was pointing to `external` and not `user_external`

**Comment by PVince81** [comment]
final build here: https://github.com/owncloud/user_external/releases/tag/v0.5.0
